apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: application
      port: 80
      targetPort: http
    - name: oauth-proxy
      port: 81
      targetPort: oauth-proxy
  selector:
    app.kubernetes.io/name: frontend